Use min in repeat, breaks Galaxy.
Breaks when try to open the tool within the Galaxy web interface, and
if try to run the unit tests:

Error - <type 'exceptions.AttributeError'>: 'ExpressionContext' object has no attribute 'keys'
URL: http://localhost:8113/tool_runner/index?tool_id=seq_filter_by_id
File '/mnt/galaxy/galaxy-central/lib/galaxy/web/framework/middleware/error.py', line 149 in __call__
  app_iter = self.application(environ, sr_checker)
File '/mnt/galaxy/galaxy-central/eggs/Paste-1.7.5.1-py2.6.egg/paste/recursive.py', line 84 in __call__
  return self.application(environ, start_response)
File '/mnt/galaxy/galaxy-central/eggs/Paste-1.7.5.1-py2.6.egg/paste/httpexceptions.py', line 633 in __call__
  return self.application(environ, start_response)
File '/mnt/galaxy/galaxy-central/lib/galaxy/web/framework/base.py', line 132 in __call__
  return self.handle_request( environ, start_response )
File '/mnt/galaxy/galaxy-central/lib/galaxy/web/framework/base.py', line 190 in handle_request
  body = method( trans, **kwargs )
File '/mnt/galaxy/galaxy-central/lib/galaxy/webapps/galaxy/controllers/tool_runner.py', line 82 in index
  template, vars = tool.handle_input( trans, params.__dict__ )
File '/mnt/galaxy/galaxy-central/lib/galaxy/tools/__init__.py', line 1882 in handle_input
  state = self.new_state( trans )
File '/mnt/galaxy/galaxy-central/lib/galaxy/tools/__init__.py', line 1810 in new_state
  self.fill_in_new_state( trans, inputs, state.inputs )
File '/mnt/galaxy/galaxy-central/lib/galaxy/tools/__init__.py', line 1819 in fill_in_new_state
  state[ input.name ] = input.get_initial_value( trans, context )
File '/mnt/galaxy/galaxy-central/lib/galaxy/tools/parameters/grouping.py', line 104 in get_initial_value
  rval_dict[ input.name ] = input.get_initial_value( trans, context )
File '/mnt/galaxy/galaxy-central/lib/galaxy/tools/parameters/basic.py', line 1042 in get_initial_value
  return SelectToolParameter.get_initial_value( self, trans, context )
File '/mnt/galaxy/galaxy-central/lib/galaxy/tools/parameters/basic.py', line 808 in get_initial_value
  if self.need_late_validation( trans, context ):
File '/mnt/galaxy/galaxy-central/lib/galaxy/tools/parameters/basic.py', line 1048 in need_late_validation
  if super( ColumnListParameter, self ).need_late_validation( trans, context ):
File '/mnt/galaxy/galaxy-central/lib/galaxy/tools/parameters/basic.py', line 789 in need_late_validation
  for layer in context.itervalues():
File '/usr/lib64/python2.6/UserDict.py', line 116 in itervalues
  for _, v in self.iteritems():
File '/usr/lib64/python2.6/UserDict.py', line 109 in iteritems
  for k in self:
File '/usr/lib64/python2.6/UserDict.py', line 96 in __iter__
  for k in self.keys():
AttributeError: 'ExpressionContext' object has no attribute 'keys'

Previously reported on the Galaxy Dev mailing list,
http://lists.bx.psu.edu/pipermail/galaxy-dev/2012-May/009627.html